name: Build & Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: node-version: '18'
      - run: npm install
      - run: npm run build
      - run: zip -r dist.zip dist
      - id: release
        uses: softprops/action-gh-release@v1
        with: tag_name: build-${{ github.run_number }}
      - uses: softprops/action-gh-release@v1
        with: files: dist.zip
        
